### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Albin-John** [eheikes/aws-tts#5]
/usr/local/lib/node_modules/aws-tts/tts.js:10
const { checkUsage, compressSpace, generateSpeech, getSpinner, trim } = require('./lib');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by eheikes** [comment]
Oops, it looks like Node didn't support destructuring until v6. Can you install Node.js v6 or higher? That should work.

**Comment by eheikes** [comment]
I have updated the docs in #7 to reflect that Node 6+ is required. Thank you for reporting this.
